language: node_js
node_js:
  - "0.10"
before_install:
  - npm install -g grunt-cli
  - npm install -g bower
install:
  - npm install
  - bower install
before_script:
  - grunt build
after_success:
  - git clone https://github.com/likr/vissec.git --branch=gh-pages tmp
  - grunt bower
  - cp -R app/* tmp
  - pushd tmp
  - git add -A
  - git commit -m 'update'
  - '[ "$TRAVIS_BRANCH" == "master" ] && [ $GH_TOKEN ] && git push --quiet https://$GH_TOKEN@github.com/likr/vissec.git gh-pages 2> /dev/null'
  - popd
env:
  global:
    - GIT_COMMITTER_NAME: 'Yosuke ONOUE'
    - GIT_COMMITTER_EMAIL: 'onoue@likr-lab.com'
    - GIT_AUTHOR_NAME: 'Yosuke ONOUE'
    - GIT_AUTHOR_EMAIL: 'onoue@likr-lab.com'
    - secure: "VYmyJE0H+RvBuAL5UxQ8xmUnaHlMRb7vDe37isHSWVBNtO4ncGJz2ZNnp/vT7fzdpoOeg4k2I1/IJm2omEpOfCih5/WKJqu6yOcCj9CWAnj9von0f8tlki1LQH/M3TzDtAbN+qE/tiKXkOKQ998VkZCZDVgwxtaeTK+gdMNcStQ="
